version: '3.8'

services:
  api:
    build: .
    container_name: unified-atlassian-platform-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=unified_atlassian_platform
    depends_on:
      - db
    networks:
      - atlassian-net

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: unified_atlassian_platform
    ports:
      - "3306:3306"
    networks:
      - atlassian-net
    volumes:
      - db-data:/var/lib/mysql

networks:
  atlassian-net:
    driver: bridge

volumes:
  db-data:
