name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./...

      - name: Build the project
        run: go build -o unified-atlassian-platform .

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: unified-atlassian-platform

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t unified-atlassian-platform:latest .

      - name: Push Docker image
        run: docker push unified-atlassian-platform:latest
